TARGET_FPS = 30
FRAME_TIME = int(1_000_000 / TARGET_FPS)

FRAME_W = 640
FRAME_H = 480
CAMERA_FORMAT = "RGB888"
CONVERT_RGB_TO_BGR = False

from pathlib import Path
import os

PROJECT_ROOT = Path(__file__).resolve().parents[1]

MODEL_PATH = str(PROJECT_ROOT / "models" / "galactic_int8_openvino_model")
CONF = 0.65
IMGSZ = 640

TRACKER_TYPE = "CSRT"
TRACKER_MAX_MISSES = 8
DETECTOR_MAX_MISSES = 15
DETECT_EVERY_N = 2
LOST_HOLD_FRAMES = 30

CENTER_BOX_W = 80
CENTER_BOX_H = 60

KP_X = 0.50
KD_X = 0.10
KP_Y = 0.50
KD_Y = 0.10

MAX_CMD_X = 1.0
MAX_CMD_Y = 1.0

ENABLE_UART = True
SERIAL_PORT = "/dev/serial0"
BAUD_RATE = 9600

AUTO_START_MODE = "AUTO"

AUTO_MAX_SPEED = 100
AUTO_MIN_SPEED = 40
AUTO_SLOW_ZONE_X = 0.35
AUTO_SLOW_ZONE_Y = 0.35
MANUAL_SPEED_START = 30
MANUAL_SPEED_STEP = 5
MANUAL_SPEED_MIN = 5
MANUAL_SPEED_MAX = 100
SPEED_ROUND_STEP = 5

BASE_LEFT_DIR = "ccw"
BASE_RIGHT_DIR = "cw"
ARM_UP_DIR = "cw"
ARM_DOWN_DIR = "ccw"

AUTO_BASE_POSITIVE_X_DIR = "cw"
AUTO_ARM_POSITIVE_Y_DIR = "cw"

MANUAL_HOLD_SECONDS = 0.18
UART_REFRESH_SECONDS = 0.40

REACQUIRE_MAX_DIST = 220
REACQUIRE_MIN_IOU = 0.04
STRONG_MATCH_IOU = 0.10
STRONG_MATCH_DIST = 120
PRINT_EVERY_N = 5

TARGET_CLASS = None
USE_CARTESIAN_Y = False
SHOW_ALL_DETECTIONS = True

SMOOTHER_TTL = 3
SMOOTHER_MATCH_DIST = 60

USE_KALMAN = True
